#app-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080