# We use the image that we have built and is not pushed (meaning it's in the local repository)
version: "3.8"

services:
  go:
    image: gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA 
    ports:
      - "80:8080"