---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-app-cert
  namespace: app
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: holded.itgaiden.com
  dnsNames:
  - holded.itgaiden.com
  secretName:  go-app-cert-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: holded.itgaiden.com
    kind: ClusterIssuer
    group: cert-manager.io