apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: holded.itgaiden.com-cert
  namespace: cert-manager
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: holded.itgaiden.com
  secretName: holded.itgaiden.com-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io