---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dbalcaraz@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-http01-key-pair
    solvers:
    - http01:
        ingress:
          class: external-nginx