apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gcloud-issuer
  namespace: cert-manager
spec:
  acme:
    email: dbalcaraz@email.com
    #server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: gcloud-issuer
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: october-cicd-go
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretName: wildcard-cert-tls
  issuerRef:
    # The issuer created previously
    name: gcloud-issuer
  dnsNames:
  - go.itgaiden.com
  #- www.itgaiden.com