--
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dbalcaraz@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stage
    http01: {}
    dns01:
      providers:
        - name: route53-dns
          cnameStrategy: "Follow"
          route53:
            accessKeyID: AKIAYYQ7G3ETMC24XIRS
            region: us-west1
            hostedZoneID: Z08597281OIP36C67X8R9
            secretAccessKeySecretRef:
              name: aws-route53-creds
              key: password.txt

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-tif
spec:
  secretName: cert-tif-tls
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  commonName: itgaiden.com
  dnsNames:
    - itgaiden.com
  acme:
    config:
      - dns01:
          provider: route53-dns
        domains:
          - itgaiden.com
