---
# Source: ingress-nginx/templates/controller-ingressclass.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.35.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: my-ing
    app.kubernetes.io/version: "0.48.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: external-nginx
spec:
  controller: k8s.io/ingress-nginx
