controller:
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"    
  ingressClass: external-nginx
  ingressClassResource:
    enabled: true
    default: false
  replicaCount: 1
  admissionWebhooks:
    enabled: true
  #service:
  #  annotations: 
  #    kubernetes.io/ingress.class: gce
  # Required for ACME
  watchIngressWithoutClass: true
  extraArgs:
    ingress-class: external-nginx